{{ if eq .Values.cluster.name "dev" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - values_dev.yaml
    path: apps/
    repoURL: https://github.com/tuananh2508/argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
